// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type CaseVersion struct {
	CaseID    string             `json:"case_id"`
	Version   int32              `json:"version"`
	Body      json.RawMessage    `json:"body"`
	Status    string             `json:"status"`
	Actor     string             `json:"actor"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID           string             `json:"id"`
	Repository   string             `json:"repository"`
	SourcePath   string             `json:"source_path"`
	CodexVersion string             `json:"codex_version"`
	ProcessedSeq int64              `json:"processed_seq"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Evidence struct {
	Seq            int64              `json:"seq"`
	ID             string             `json:"id"`
	ConversationID string             `json:"conversation_id"`
	TurnID         string             `json:"turn_id"`
	Kind           string             `json:"kind"`
	OccurredAt     string             `json:"occurred_at"`
	SourceOffset   int64              `json:"source_offset"`
	BlobHash       string             `json:"blob_hash"`
	ByteCount      int64              `json:"byte_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID             string             `json:"id"`
	ConversationID string             `json:"conversation_id"`
	FromSeq        int64              `json:"from_seq"`
	ThroughSeq     int64              `json:"through_seq"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	LeaseToken     pgtype.Text        `json:"lease_token"`
	Error          string             `json:"error"`
	PacketHash     pgtype.Text        `json:"packet_hash"`
	ResultHash     pgtype.Text        `json:"result_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type LearningCase struct {
	ID             string             `json:"id"`
	ConversationID string             `json:"conversation_id"`
	Version        int32              `json:"version"`
	Status         string             `json:"status"`
	Body           json.RawMessage    `json:"body"`
	JobID          string             `json:"job_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SchemaMigration struct {
	Version   int32              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Turn struct {
	ConversationID     string      `json:"conversation_id"`
	ID                 string      `json:"id"`
	StartEvidenceID    pgtype.Text `json:"start_evidence_id"`
	CompleteEvidenceID pgtype.Text `json:"complete_evidence_id"`
	CompletionSeq      pgtype.Int8 `json:"completion_seq"`
	Status             string      `json:"status"`
}
