// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortTurn = `-- name: AbortTurn :exec
INSERT INTO turns(conversation_id,id,status) VALUES($1,$2,'aborted')
ON CONFLICT(conversation_id,id) DO UPDATE SET status=CASE WHEN turns.status='completed' THEN 'completed' ELSE 'aborted' END
`

type AbortTurnParams struct {
	ConversationID string `json:"conversation_id"`
	ID             string `json:"id"`
}

func (q *Queries) AbortTurn(ctx context.Context, arg AbortTurnParams) error {
	_, err := q.db.Exec(ctx, abortTurn, arg.ConversationID, arg.ID)
	return err
}

const caseHistory = `-- name: CaseHistory :many
SELECT case_id, version, body, status, actor, reason, created_at FROM case_versions WHERE case_id=$1 ORDER BY version
`

func (q *Queries) CaseHistory(ctx context.Context, caseID string) ([]CaseVersion, error) {
	rows, err := q.db.Query(ctx, caseHistory, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaseVersion
	for rows.Next() {
		var i CaseVersion
		if err := rows.Scan(
			&i.CaseID,
			&i.Version,
			&i.Body,
			&i.Status,
			&i.Actor,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET status='running', attempt=attempt+1,
 lease_until=now()+$1::integer * interval '1 second', lease_token=$2::text
WHERE id=(SELECT id FROM jobs WHERE
 ((status IN ('queued','retry','blocked_by_codex') AND next_run_at<=now()) OR (status='running' AND lease_until<now()))
 AND attempt < $3::integer
 ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING id, conversation_id, from_seq, through_seq, status, attempt, next_run_at, lease_until, lease_token, error, packet_hash, result_hash, created_at, completed_at
`

type ClaimJobParams struct {
	LeaseSeconds int32  `json:"lease_seconds"`
	Token        string `json:"token"`
	MaxAttempts  int32  `json:"max_attempts"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.LeaseSeconds, arg.Token, arg.MaxAttempts)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FromSeq,
		&i.ThroughSeq,
		&i.Status,
		&i.Attempt,
		&i.NextRunAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.Error,
		&i.PacketHash,
		&i.ResultHash,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeTurn = `-- name: CompleteTurn :exec
INSERT INTO turns(conversation_id,id,complete_evidence_id,completion_seq,status) VALUES($1,$2,$3,$4,'completed')
ON CONFLICT(conversation_id,id) DO UPDATE SET complete_evidence_id=COALESCE(turns.complete_evidence_id,EXCLUDED.complete_evidence_id),
completion_seq=COALESCE(turns.completion_seq,EXCLUDED.completion_seq),status='completed'
`

type CompleteTurnParams struct {
	ConversationID     string      `json:"conversation_id"`
	ID                 string      `json:"id"`
	CompleteEvidenceID pgtype.Text `json:"complete_evidence_id"`
	CompletionSeq      pgtype.Int8 `json:"completion_seq"`
}

func (q *Queries) CompleteTurn(ctx context.Context, arg CompleteTurnParams) error {
	_, err := q.db.Exec(ctx, completeTurn,
		arg.ConversationID,
		arg.ID,
		arg.CompleteEvidenceID,
		arg.CompletionSeq,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status=$3,error=$4,next_run_at=now()+interval '60 seconds',lease_until=NULL,lease_token=NULL
WHERE id=$1 AND lease_token=$2
`

type FailJobParams struct {
	ID         string      `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
	Status     string      `json:"status"`
	Error      string      `json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob,
		arg.ID,
		arg.LeaseToken,
		arg.Status,
		arg.Error,
	)
	return err
}

const getCase = `-- name: GetCase :one
SELECT id, conversation_id, version, status, body, job_id, updated_at FROM learning_cases WHERE id=$1
`

func (q *Queries) GetCase(ctx context.Context, id string) (LearningCase, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i LearningCase
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Version,
		&i.Status,
		&i.Body,
		&i.JobID,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, repository, source_path, codex_version, processed_seq, created_at FROM conversations WHERE id=$1
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.SourcePath,
		&i.CodexVersion,
		&i.ProcessedSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidence = `-- name: GetEvidence :one
SELECT seq, id, conversation_id, turn_id, kind, occurred_at, source_offset, blob_hash, byte_count, created_at FROM evidence WHERE id=$1
`

func (q *Queries) GetEvidence(ctx context.Context, id string) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, id)
	var i Evidence
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ConversationID,
		&i.TurnID,
		&i.Kind,
		&i.OccurredAt,
		&i.SourceOffset,
		&i.BlobHash,
		&i.ByteCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :one
INSERT INTO evidence(id,conversation_id,turn_id,kind,occurred_at,source_offset,blob_hash,byte_count)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET id=EXCLUDED.id RETURNING seq
`

type InsertEvidenceParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	TurnID         string `json:"turn_id"`
	Kind           string `json:"kind"`
	OccurredAt     string `json:"occurred_at"`
	SourceOffset   int64  `json:"source_offset"`
	BlobHash       string `json:"blob_hash"`
	ByteCount      int64  `json:"byte_count"`
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvidence,
		arg.ID,
		arg.ConversationID,
		arg.TurnID,
		arg.Kind,
		arg.OccurredAt,
		arg.SourceOffset,
		arg.BlobHash,
		arg.ByteCount,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const listCases = `-- name: ListCases :many
SELECT id, conversation_id, version, status, body, job_id, updated_at FROM learning_cases ORDER BY updated_at DESC LIMIT 100
`

func (q *Queries) ListCases(ctx context.Context) ([]LearningCase, error) {
	rows, err := q.db.Query(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningCase
	for rows.Next() {
		var i LearningCase
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Version,
			&i.Status,
			&i.Body,
			&i.JobID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.repository, c.source_path, c.codex_version, c.processed_seq, c.created_at, count(t.id)::bigint AS completed_turns,
 count(t.id) FILTER (WHERE t.completion_seq > c.processed_seq)::bigint AS pending_turns
FROM conversations c LEFT JOIN turns t ON t.conversation_id=c.id AND t.status='completed'
GROUP BY c.id ORDER BY c.created_at
`

type ListConversationsRow struct {
	ID             string             `json:"id"`
	Repository     string             `json:"repository"`
	SourcePath     string             `json:"source_path"`
	CodexVersion   string             `json:"codex_version"`
	ProcessedSeq   int64              `json:"processed_seq"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedTurns int64              `json:"completed_turns"`
	PendingTurns   int64              `json:"pending_turns"`
}

func (q *Queries) ListConversations(ctx context.Context) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.SourcePath,
			&i.CodexVersion,
			&i.ProcessedSeq,
			&i.CreatedAt,
			&i.CompletedTurns,
			&i.PendingTurns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidence = `-- name: ListEvidence :many
SELECT seq, id, conversation_id, turn_id, kind, occurred_at, source_offset, blob_hash, byte_count, created_at FROM evidence WHERE conversation_id=$1 ORDER BY seq LIMIT $2
`

type ListEvidenceParams struct {
	ConversationID string `json:"conversation_id"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListEvidence(ctx context.Context, arg ListEvidenceParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidence, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ConversationID,
			&i.TurnID,
			&i.Kind,
			&i.OccurredAt,
			&i.SourceOffset,
			&i.BlobHash,
			&i.ByteCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, conversation_id, from_seq, through_seq, status, attempt, next_run_at, lease_until, lease_token, error, packet_hash, result_hash, created_at, completed_at FROM jobs ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.FromSeq,
			&i.ThroughSeq,
			&i.Status,
			&i.Attempt,
			&i.NextRunAt,
			&i.LeaseUntil,
			&i.LeaseToken,
			&i.Error,
			&i.PacketHash,
			&i.ResultHash,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurns = `-- name: ListTurns :many
SELECT conversation_id, id, start_evidence_id, complete_evidence_id, completion_seq, status FROM turns WHERE conversation_id=$1 ORDER BY completion_seq NULLS LAST, id
`

func (q *Queries) ListTurns(ctx context.Context, conversationID string) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listTurns, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.StartEvidenceID,
			&i.CompleteEvidenceID,
			&i.CompletionSeq,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs SET status='queued', attempt=0, error='', next_run_at=now(), lease_until=NULL, lease_token=NULL
WHERE id=$1 AND status NOT IN ('running','succeeded')
`

func (q *Queries) RetryJob(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPacket = `-- name: SetPacket :execrows
UPDATE jobs SET packet_hash=$3 WHERE id=$1 AND lease_token=$2
`

type SetPacketParams struct {
	ID         string      `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
	PacketHash pgtype.Text `json:"packet_hash"`
}

func (q *Queries) SetPacket(ctx context.Context, arg SetPacketParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPacket, arg.ID, arg.LeaseToken, arg.PacketHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startTurn = `-- name: StartTurn :exec
INSERT INTO turns(conversation_id,id,start_evidence_id,status) VALUES($1,$2,$3,'started')
ON CONFLICT(conversation_id,id) DO UPDATE SET start_evidence_id=COALESCE(turns.start_evidence_id,EXCLUDED.start_evidence_id)
`

type StartTurnParams struct {
	ConversationID  string      `json:"conversation_id"`
	ID              string      `json:"id"`
	StartEvidenceID pgtype.Text `json:"start_evidence_id"`
}

func (q *Queries) StartTurn(ctx context.Context, arg StartTurnParams) error {
	_, err := q.db.Exec(ctx, startTurn, arg.ConversationID, arg.ID, arg.StartEvidenceID)
	return err
}

const upsertConversation = `-- name: UpsertConversation :exec
INSERT INTO conversations(id, repository, source_path, codex_version) VALUES ($1,$2,$3,$4)
ON CONFLICT(id) DO NOTHING
`

type UpsertConversationParams struct {
	ID           string `json:"id"`
	Repository   string `json:"repository"`
	SourcePath   string `json:"source_path"`
	CodexVersion string `json:"codex_version"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.Exec(ctx, upsertConversation,
		arg.ID,
		arg.Repository,
		arg.SourcePath,
		arg.CodexVersion,
	)
	return err
}
